### ISSUE TITLE
如何把weather-description的语言改为中文？

### ISSUE THREAD

**Issue by 1042799521** [hrtovey/weather-app#1]
如何把weather-description的语言改为中文？

**Comment by hrtovey** [comment]
I used navigator.language or navigator.userLanguage to call the api with the correct language. The weather description should be in different languages now. I'll continue reading about this to see what more I can do. Thank you!

![i18n](https://cloud.githubusercontent.com/assets/5010287/12222804/f68c1086-b783-11e5-9802-9164510aca01.png)
